"""Add NotificationOutbox

Revision ID: 0274546f8805
Revises: f029e63fc80f
Create Date: 2026-09-19 00:17:53.804596
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0274546f8805'
down_revision: Union[str, None] = 'f029e63fc80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parse_mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_outbox_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_outbox_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index('ix_notification_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_status')
        batch_op.drop_index(batch_op.f('ix_notification_outbox_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_notification_outbox_status'))

    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
