"""v5_production_schema

Revision ID: 029295522680
Revises: 0274546f8805
Create Date: 2026-09-19 01:35:48.336576
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029295522680'
down_revision: Union[str, None] = '0274546f8805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['seller_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_telegram_id', name='uq_seller_group_members')
    )
    with op.batch_alter_table('seller_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_group_members_user_telegram_id'), ['user_telegram_id'], unique=False)

    with op.batch_alter_table('balance_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('held_before', sa.Text(), nullable=False, server_default='0.00'))
        batch_op.add_column(sa.Column('held_after', sa.Text(), nullable=False, server_default='0.00'))

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_markup_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dedupe_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('next_attempt_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_notification_outbox_dedupe_key', ['dedupe_key'])
        batch_op.drop_column('processed_at')
        batch_op.drop_column('error_details')

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_notification_outbox_dedupe_key', type_='unique')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('last_error')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('lease_token')
        batch_op.drop_column('next_attempt_at')
        batch_op.drop_column('attempts')
        batch_op.drop_column('dedupe_key')
        batch_op.drop_column('kind')
        batch_op.drop_column('reply_markup_json')

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('state')
        batch_op.drop_column('fingerprint')

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('balance_ledger', schema=None) as batch_op:
        batch_op.drop_column('held_after')
        batch_op.drop_column('held_before')

    with op.batch_alter_table('seller_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_group_members_user_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_seller_group_members_group_id'))

    op.drop_table('seller_group_members')
    # ### end Alembic commands ###
