"""Plan v4 concurrency and financial fields

Revision ID: e80e09802b9f
Revises: 001
Create Date: 2026-09-18 21:50:44.676448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80e09802b9f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_restrictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desired_state', sa.String(length=10), server_default='ON', nullable=False))
        batch_op.add_column(sa.Column('actual_state', sa.String(length=10), server_default='OFF', nullable=False))
        batch_op.add_column(sa.Column('operation_token', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('worker_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('held_for_withdrawal', sa.Text(), server_default='0.00', nullable=False))

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))

    # Update partial unique index for live tasks
    op.drop_index('uix_active_task_user_target', table_name='campaign_tasks')
    op.create_index('uix_active_task_user_target', 'campaign_tasks', ['user_telegram_id', 'target_chat_id'], unique=True, sqlite_where=sa.text("status IN ('active', 'pending_restriction')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('worker_token')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('held_for_withdrawal')

    with op.batch_alter_table('user_restrictions', schema=None) as batch_op:
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('worker_token')
        batch_op.drop_column('operation_token')
        batch_op.drop_column('actual_state')
        batch_op.drop_column('desired_state')

    # ### end Alembic commands ###

    op.drop_index('uix_active_task_user_target', table_name='campaign_tasks')
    op.create_index('uix_active_task_user_target', 'campaign_tasks', ['user_telegram_id', 'target_chat_id'], unique=True, sqlite_where=sa.text("status = 'active'"))
