"""Add transactional fencing to models

Revision ID: e8ddf0323610
Revises: 029295522680
Create Date: 2026-09-19 02:17:04.599513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ddf0323610'
down_revision: Union[str, None] = '029295522680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_action')
        batch_op.drop_index('ix_audit_actor')
        batch_op.drop_index('ix_audit_created')
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_telegram_id'), ['actor_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('balance_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_idem')
        batch_op.create_index(batch_op.f('ix_balance_ledger_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_balance_ledger_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('campaign_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_campaign_tasks_group')
        batch_op.drop_index('ix_campaign_tasks_target_chat')
        batch_op.create_index(batch_op.f('ix_campaign_tasks_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tasks_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tasks_target_chat_id'), ['target_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tasks_user_telegram_id'), ['user_telegram_id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_user')
        batch_op.create_index(batch_op.f('ix_campaigns_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_target_chat_id'), ['target_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('claim_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_deposits_invoice')
        batch_op.create_index(batch_op.f('ix_deposits_invoice_id'), ['invoice_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deposits_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_key')
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=True)

    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('claim_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=False))
        batch_op.drop_column('lease_token')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_payouts_user')
        batch_op.drop_index('ix_payouts_withdrawal')
        batch_op.create_index(batch_op.f('ix_payouts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_withdrawal_id'), ['withdrawal_id'], unique=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index('ix_refunds_campaign')
        batch_op.drop_index('ix_refunds_user')
        batch_op.create_index(batch_op.f('ix_refunds_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('seller_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_seller_groups_chat')
        batch_op.drop_index('ix_seller_groups_user')
        batch_op.create_index(batch_op.f('ix_seller_groups_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_groups_telegram_chat_id'), ['telegram_chat_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_seller_groups_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('system_errors', schema=None) as batch_op:
        batch_op.drop_index('ix_errors_created')
        batch_op.create_index(batch_op.f('ix_system_errors_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('target_user_history', schema=None) as batch_op:
        batch_op.drop_index('ix_target_history_target')
        batch_op.drop_index('ix_target_history_user')
        batch_op.create_index(batch_op.f('ix_target_user_history_target_chat_id'), ['target_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_user_history_user_telegram_id'), ['user_telegram_id'], unique=False)

    with op.batch_alter_table('user_restrictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('claim_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=False))
        batch_op.drop_column('operation_token')
        batch_op.drop_column('worker_token')

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('claim_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_withdrawals_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('worker_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_token', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_withdrawals_user_id'))
        batch_op.drop_column('generation')
        batch_op.drop_column('claim_token')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('user_restrictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_token', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('operation_token', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('generation')
        batch_op.drop_column('claim_token')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('target_user_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_user_history_user_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_target_user_history_target_chat_id'))
        batch_op.create_index('ix_target_history_user', ['user_telegram_id'], unique=False)
        batch_op.create_index('ix_target_history_target', ['target_chat_id'], unique=False)

    with op.batch_alter_table('system_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_errors_created_at'))
        batch_op.create_index('ix_errors_created', ['created_at'], unique=False)

    with op.batch_alter_table('seller_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_groups_user_id'))
        batch_op.drop_index(batch_op.f('ix_seller_groups_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_seller_groups_category_id'))
        batch_op.create_index('ix_seller_groups_user', ['user_id'], unique=False)
        batch_op.create_index('ix_seller_groups_chat', ['telegram_chat_id'], unique=1)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_user_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_campaign_id'))
        batch_op.create_index('ix_refunds_user', ['user_id'], unique=False)
        batch_op.create_index('ix_refunds_campaign', ['campaign_id'], unique=False)

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_withdrawal_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_user_id'))
        batch_op.create_index('ix_payouts_withdrawal', ['withdrawal_id'], unique=False)
        batch_op.create_index('ix_payouts_user', ['user_id'], unique=False)

    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_token', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_column('generation')
        batch_op.drop_column('claim_token')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))
        batch_op.create_index('ix_idempotency_key', ['key'], unique=1)

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_user_id'))

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposits_user_id'))
        batch_op.drop_index(batch_op.f('ix_deposits_invoice_id'))
        batch_op.create_index('ix_deposits_invoice', ['invoice_id'], unique=1)
        batch_op.drop_column('generation')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('claim_token')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_target_chat_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_category_id'))
        batch_op.create_index('ix_campaigns_user', ['user_id'], unique=False)

    with op.batch_alter_table('campaign_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_tasks_user_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_tasks_target_chat_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_tasks_group_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_tasks_campaign_id'))
        batch_op.create_index('ix_campaign_tasks_target_chat', ['target_chat_id'], unique=False)
        batch_op.create_index('ix_campaign_tasks_group', ['group_id'], unique=False)

    with op.batch_alter_table('balance_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_balance_ledger_idempotency_key'))
        batch_op.create_index('ix_ledger_idem', ['idempotency_key'], unique=1)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_actor', ['actor_telegram_id'], unique=False)
        batch_op.create_index('ix_audit_action', ['action'], unique=False)

    # ### end Alembic commands ###
