"""Add recipient_telegram_id and uix_live_withdrawal_user

Revision ID: f029e63fc80f
Revises: b28855b9651a
Create Date: 2026-09-19 00:07:41.219970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f029e63fc80f'
down_revision: Union[str, None] = 'b28855b9651a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_telegram_id', sa.BigInteger(), nullable=True))
        batch_op.create_index('uix_live_withdrawal_user', ['user_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'approved', 'processing')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index('uix_live_withdrawal_user', sqlite_where=sa.text("status IN ('pending', 'approved', 'processing')"))
        batch_op.drop_column('recipient_telegram_id')

    # ### end Alembic commands ###
